
[workspace]
resolver = "3"

members = [
    "chat-cli",
    "conversations",
    "crypto",
    "double-ratchets",
    "storage",
]

[workspace.dependencies]
blake2 = "0.10"
storage = { path = "storage" }
