
[workspace]
resolver = "3"

members = [
    "conversations",
    "crypto",
    "double-ratchets",
    "storage",
]

[workspace.dependencies]
blake2 = "0.10"
storage = { path = "storage" }

# Internal crates
crypto = { path = "crypto" }
